### ISSUE TITLE
bob is before leap in exercise order

### ISSUE THREAD

**Issue by stevejb71** [exercism/xcpp#124]
Bob is a fair bit harder IMO. Other tracks (such as xhaskell, xocaml) have bob after leap.

**Comment by patricksjackson** [comment]
All of the exercises really need to be reordered at some point. I took a swag at estimating the difficulty and topics for all the exercises here a month ago, but I didn't get around to changing the order.

I don't just want to reorder them based solely on my swag difficulty ratings, both because I don't fully trust them and because I haven't yet taken the time to understand if there's a good ordering for the exercises that build on top of each other.

I am fully open to accepting PR's that make obvious fixes like the one above 👍

**Comment by stevejb71** [comment]
I added PR #127 for this.

**Comment by patricksjackson** [comment]
Merged the linked PR so I'm closing this. Thanks!
