### ISSUE TITLE
Incomplete description for problem phone_number

### ISSUE THREAD

**Issue by ekse** [exercism/xcpp#47]
The description for the phone_number problem does not match the tests. The description talks about invalid phone numbers but does not mention how to deal with this case and there are no tests for it (raise exception?). There is a test related to `area_code` which is not mentioned in the description.

**Comment by kytrinyx** [comment]
The README is pretty ambiguous on purpose, though it probably should mention area codes for US/Canadian numbers.

I'm not sure what the right move is for the invalid phone numbers. I think different languages handle it differently. Go returns error values, I believe, and Ruby raises an ArgumentError.

**Comment by ekse** [comment]
In general I think the problem descriptions should describe the expected interface and be deliberately ambiguous on the implementation. In this case I would add a mention of `area_code`. The tests handle invalid numbers by returning "0000000000" which is fine but should also be mentioned in the description.

**Comment by LegalizeAdulthood** [comment]
The expected interface can be different for different languages which is why it's not in the problem description.  As just a small example, the expected interface for a functional language is very different from an object-oriented language with exceptions, which in turn is very different for a procedural language without an exception mechanism.

The expected interface is defined by the tests and the problem description is purposefully kept vague enough that it doesn't try to prescribe any particular implementation.

**Comment by LegalizeAdulthood** [comment]
Also, the C++ language track defines what the expected behavior is when invalid phone numbers are given.  This is covered in tests such as [invalid_when_11_digits](https://github.com/exercism/xcpp/blob/master/phone-number/phone_number_test.cpp#L27).

**Comment by ekse** [comment]
Closing this issue as it is not related directly to the C++ track.
