### ISSUE TITLE
food_chain::sing() test

### ISSUE THREAD

**Issue by NobbZ** [exercism/xcpp#49]
The last test of the “food_chain” problem is defined as follows:

```cpp
BOOST_AUTO_TEST_CASE(the_whole_song)
{
    BOOST_REQUIRE_EQUAL(food_chain::verses(1, 8), food_chain::sing());
}
```

This has some flaws:
* It reveals the easiest, most idiomatic, best solution on how to implement `sing`.
* you can't fail it, because you just copy the expectation.

So this test should either be removed or `expect` should be hardcoded/loaded from auch file.

**Comment by LegalizeAdulthood** [comment]
It is not a function of tests to obscure salient facts about the implementation.  It is not a flaw if a test reveals the easiest, most idiomatic, best solution for an implementation.  Quite the contrary, that is an awesome test if it reveals that!  This test reveals exactly the requirements of the `sing` function -- it should output the same as requesting verses 1 through 8.

As for the assertion that you can't fail this test, I submit that you aren't practicing actual test-driven development if you don't know how to fail this test.  When practicing strict TDD, you follow these three rules:

1. You are not allowed to write any production code unless it is to make a failing unit test pass.
1. You are not allowed to write any more of a unit test than is sufficient to fail; and compilation failures are failures.
1. You are not allowed to write any more production code than is sufficient to pass the one failing unit test.

Let's see how this would apply to this test case.  First, I have a compilation failure because I haven't written the function `food_chain::sing()`.  OK, so I do the minimal amount of coding needed to get past the compile error:

```
std::string food_chain::sing()
{
    throw std;:runtime_error("not implemented");
}
```

Now I have an implementation that compiles, but the test fails at run time.  I then can implement something in the body of the function to make the test pass.  There are a number of ways you can pass this test, the most obvious being a giant copy/paste of the entire text and returning it as a literal string.

I see nothing wrong with the test expressing the required output of one function in terms of another function.  Contrast this to the [javascript test](https://github.com/exercism/xjavascript/blob/master/food-chain/food-chain_test.spec.js) where this simple fact is obscured by the giant multi-line construction of the expected text.  Either way you end up with duplication between the test and the implementation.  In the JavaScript test, the duplication takes the form of a giant constructed string.  In the C++ test the duplication is expressed in terms of the function that has just been built.
